#!/bin/bash

# change the core names to your liking
core_names="tst acc prd"

# change to new versions if needed
apache_solr_version="3.6.2"
search_api_solr_version="7.x-1.0-rc3"




wget http://apache.hippo.nl/lucene/solr/$apache_solr_version/apache-solr-$apache_solr_version.tgz
tar -xzf apache-solr-$apache_solr_version.tgz 
cp -r apache-solr-$apache_solr_version/example solr
wget http://ftp.drupal.org/files/projects/search_api_solr-7.x-1.0-rc3.tar.gz
tar -xzf search_api_solr-$search_api_solr_version.tar.gz
# first copy schema & solrconfig
cp search_api_solr/solr-conf/3.x/* solr/solr/conf/

# create multicore nodes
for c in $core_names
do
  echo "Creating $c core"
  mkdir solr/solr/$c
  cp -r solr/solr/conf solr/solr/$c/
  # create configiration text
  cores=$(cat <<EOF
$cores
    <core name="$c" instanceDir="$c" />
EOF
)
done

#create logfile for Jetty
touch solr/solr.log

# create multicore solr.xml
cat >solr/solr/solr.xml <<- EOT
<?xml version="1.0" encoding="UTF-8" ?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<!--
   This is an example of a simple "solr.xml" file for configuring one or 
   more Solr Cores, as well as allowing Cores to be added, removed, and 
   reloaded via HTTP requests.

   More information about options available in this configuration file, 
   and Solr Core administration can be found online:
   http://wiki.apache.org/solr/CoreAdmin
-->

<!--
 All (relative) paths are relative to the installation path
  
  persistent: Save changes made via the API to this file
  sharedLib: path to a lib directory that will be shared across all cores
-->
<solr persistent="false">

  <!--
  adminPath: RequestHandler path to manage cores.  
    If 'null' (or absent), cores will not be manageable via request handler
  -->
  <cores adminPath="/admin/cores">
  $cores
  </cores>
</solr>
EOT
